version: '3.4'

services:
  identityservice:
    container_name: c_identityservice
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/IdentityService/Dockerfile

  catalogservice.api:
    container_name: c_catalogservice
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: Services/CatalogService/CatalogService.Api/Dockerfile

  ocrservice.api:
    container_name: c_ocrservice
    image: ${DOCKER_REGISTRY-}ocrserviceapi
    build:
      context: .
      dockerfile: Services/OCRService/OCRService.Api/Dockerfile

  catalogseeder.api:
    container_name: c_catalogseeder
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: Services/CatalogService/CatalogService.Api/Dockerfile


  fileapiservice.api:
    container_name: c_fileapiservice
    image: ${DOCKER_REGISTRY-}fileapiserviceapi
    build:
      context: .
      dockerfile: Services/FileApiService/FileApiService.Api/Dockerfile

  web.apigateway:
    container_name: c_apigateway
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/AppGateways/WebAppGateway/Web.ApiGateway/Dockerfile

  webapp:
    container_name: c_blazorui
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/Client/BlazorWebApp/WebApp/Dockerfile

  nginx.public:
    container_name: c_nginx_public
    build:
      context: ./Nginx
      dockerfile: Dockerfile


   

  s_rabbitmq:
     container_name: c_rabbitmq
     image: rabbitmq:3-management

  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  s_consul:
    container_name: c_consul
    image: consul:1.15

 

