server {
    listen 80;
    server_name digitalaccounting.tr www.digitalaccounting.tr;

    root /var/www/web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
