events { }

http {
    include mime.types;

    types {
        application/wasm wasm;  # Blazor için gerekli (WebAssembly MIME türü)
    }

    server {
        listen 2000;

        location / {
            root /var/www/web/;  # Burada Blazor publish edilen içerik olmalı (index.html, dll, js, wasm)
            try_files $uri $uri/ /index.html =404;  # SPA yönlendirme
        }
    }
}
