user root;
worker_processes auto;
worker_rlimit_nofile 100000;
pid /run/nginx.pid;

events {
    worker_connections 4096;
    multi_accept on;
    use epoll;
}

http {
    # Temel Ayarlar
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 30;
    keepalive_requests 100000;
    types_hash_max_size 2048;
    server_tokens off;

    # MIME türleri
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Log Formatı
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main buffer=16k;
    error_log /var/log/nginx/error.log warn;

    # Gzip Sıkıştırma
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types
        application/atom+xml
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/xml
        font/opentype
        image/svg+xml
        text/css
        text/javascript
        text/plain
        text/xml;

    # Dosya Önbelleği
    open_file_cache max=2000 inactive=20s;
    open_file_cache_valid 60s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;

    # SSL Ayarları
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Proxy Cache Path
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=asset_cache:10m inactive=7d max_size=2g use_temp_path=off;

    map_hash_max_size 8192;
    map_hash_bucket_size 128;

   

    # conf.d dizinini dahil et (yeni configlerin etkin olması için)
    include /etc/nginx/conf.d/*.conf;
}
