<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d7ce1281-a7db-4206-a5da-cc932d34b0b7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Vision.V1" Version="3.7.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
	<PackageReference Include="Consul" Version="1.7.14.7" />
	<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />

	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />

	  <PackageReference Include="Serilog" Version="4.3.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.1-dev-02317" />
	  <PackageReference Include="Serilog.Sinks.Graylog" Version="3.1.1" />
  </ItemGroup>

</Project>
